import React from 'react'
import type {JevTrace} from '../core/contract.ts'
import {conversation,stageName,statusName,type TraceFilters} from './view-model.ts'
import {requestLeave} from '../../../dsh-plugin-manager/src/client/workbench-navigation.ts'
import s from '../../../dsh-client-ui-plain-chat/src/client/ManagedCapabilities.module.css'
import css from './JevControls.module.css'
export function JevTraceDetail({trace,open,onToggle}:{trace:JevTrace;open?:boolean;onToggle?:(open:boolean)=>void}){return <details className={css.trace} open={open} onToggle={e=>onToggle?.(e.currentTarget.open)}><summary>{stageName[trace.stage]} · {statusName[trace.status]} · {trace.summary}</summary><p className={s.muted}>{new Date(trace.at).toLocaleString()} · {(trace.elapsedMs/1000).toFixed(1)} 秒 · 配置 v{trace.revision}</p>{trace.decision?.checks.map((c,i)=><p key={i}>{c.criterion}：{({supported:'有依据',uncertain:'待核对',unsupported:'缺少依据'})[c.verdict]}。{c.evidence}</p>)}{trace.decision?.missing.map((m,i)=><p key={i}>待确认：{m}</p>)}{trace.status!=='allowed'&&<p className={s.notice}>{trace.status==='clarify'?'补充待确认信息后发起新一轮。':trace.status==='blocked'?'核对目标、权限和依据后再继续；已经完成的操作不会自动撤销。':'检查取消、超时或失败时，不会自动视为通过；可在设置中检查模型，之后重试任务。'}</p>}{!!trace.attempts?.length&&<ol className={css.attempts}>{trace.attempts.map((a,i)=><li key={i}>{a.model} · {a.summary} · {(a.elapsedMs/1000).toFixed(1)} 秒</li>)}</ol>}<details><summary>技术信息</summary><p>模型：{trace.config.model}<br/>会话：{trace.scope}<br/>轮次：{trace.runId}</p></details></details>}
export function JevTraces({traces,filters,setFilters,expanded,setExpanded}:{traces:JevTrace[];filters:TraceFilters;setFilters:(value:TraceFilters)=>void;expanded:string[];setExpanded:(ids:string[])=>void}){
  const filtered=traces.filter(t=>(!filters.stage||t.stage===filters.stage)&&(!filters.status||t.status===filters.status)&&(!filters.days||Date.parse(t.at)>=Date.now()-Number(filters.days)*86400000)&&(!filters.query||[conversation(t.scope).name,t.summary,t.config.model,...(t.attempts?.map(a=>a.model)??[])].some(s=>s.toLowerCase().includes(filters.query.toLowerCase()))))
  const groups=new Map<string,JevTrace[]>();for(const trace of filtered.slice().reverse())groups.set(trace.runId,[...(groups.get(trace.runId)??[]),trace])
  return <><div className={`${s.fields} ${css.filters}`}><label className={s.field}>搜索会话或摘要<input value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/></label><label className={s.field}>阶段<select value={filters.stage} onChange={e=>setFilters({...filters,stage:e.target.value})}><option value="">全部阶段</option>{Object.entries(stageName).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className={s.field}>结果<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部结果</option>{Object.entries(statusName).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className={s.field}>时间<select value={filters.days} onChange={e=>setFilters({...filters,days:e.target.value})}><option value="">全部时间</option><option value="1">最近一天</option><option value="7">最近七天</option><option value="30">最近三十天</option></select></label></div><p className={s.muted}>本地最多保留最近 200 项，当前匹配 {filtered.length} 项。按会话轮次分组，展示判断依据摘要。</p>{[...groups].map(([id,items])=>{const target=conversation(items[0]!.scope);return <article key={id} className={s.card}><div className={s.heading}><strong>{target.name}</strong>{target.open&&<button className={s.button} onClick={()=>{if(requestLeave())target.open?.()}}>返回对话 ↗</button>}</div><small className={s.muted}>{new Date(items.at(-1)!.at).toLocaleString()} 开始的检查 · {items.length} 项</small>{items.map(trace=><JevTraceDetail key={trace.id} trace={trace} open={expanded.includes(trace.id)} onToggle={open=>setExpanded(open?[...new Set([...expanded,trace.id])]:expanded.filter(id=>id!==trace.id))}/>)}</article>})}{!filtered.length&&<p className={s.empty}>暂无匹配的检查记录。连接检查的结果位于“配置与状态”；任务记录在开启后的新轮次中产生。</p>}</>
}
