// @vitest-environment node
import {afterEach,describe,expect,it} from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {ManagedSkills} from '../src/managed.ts'
import {collectSkills} from '../src/collect.ts'
import {packageZip} from '../../dsh-capabilities/src/host/package-archive.ts'
const roots:string[]=[]
afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true})})
function fixture(){const home=fs.mkdtempSync(path.join(os.tmpdir(),'managed-skills-'));roots.push(home);const project=path.join(home,'project');fs.mkdirSync(project);return {home,project,service:new ManagedSkills(home,()=>[project])}}
const text=(name='demo',body='Use the template.')=>`---\nname: ${name}\ndescription: A reusable skill\n---\n${body}\n`
const payload=(content=text())=>({scope:'global',files:[{path:'demo/SKILL.md',data:Buffer.from(content).toString('base64')},{path:'demo/resources/template.txt',data:Buffer.from('original resource').toString('base64')}]})
function install(service:ManagedSkills,content=text()){const p=service.inspect(payload(content));service.commit(p.id,[{key:p.candidates[0].key,mode:'update'}],true);return service.read().skills[0]}
describe('managed skill distribution',()=>{
 it('persists favorites across updates without rewriting active skill bytes',()=>{const {service}=fixture(),row=install(service),file=path.join(row.root,row.name,'SKILL.md'),before=fs.readFileSync(file);service.change(row.id,service.read().revision,'pinned',true);expect(fs.readFileSync(file)).toEqual(before);install(service,text('demo','Updated'));expect(service.read().skills[0].pinned).toBe(true)})
 it('previews bounded UTF-8 resources while stopped and rejects missing or escaping paths',()=>{const {service}=fixture(),row=install(service);service.change(row.id,service.read().revision,'enabled',false);expect(service.resource(row.id,'resources/template.txt').content).toBe('original resource');expect(()=>service.resource(row.id,'../state.json')).toThrow();expect(()=>service.resource(row.id,'missing.txt')).toThrow('资源不存在');expect(service.read().skills[0].enabled).toBe(false)})
 it('rejects duplicate YAML keys and preserves valid block scalars when copying',()=>{const {service}=fixture();const bad=service.inspect(payload(text().replace('name: demo','name: demo\nname: second')));expect(bad.candidates[0].error).toContain('重复');service.discard(bad.id);const p=service.inspect(payload('---\nname: |\n  demo\ndescription: >\n  Long description\n  continues here\n---\nBody'));expect(p.candidates[0].error).toBeTruthy();service.discard(p.id);const good=service.inspect(payload(text().replace('A reusable skill','>\n  Long description\n  continues here')));service.commit(good.id,[{key:good.candidates[0].key,mode:'copy',name:'copy'}],true);expect(service.read().skills[0].description).toContain('Long description continues here')})
 it('preserves resources and exposes real filesystem invocation flags after toggle and restart',async()=>{const {home,service}=fixture(),row=install(service);expect(fs.readFileSync(path.join(row.root,row.name,'resources/template.txt'),'utf8')).toBe('original resource');const collect=()=>collectSkills({cwd:home,projectRoots:[],dshHome:home,agentsHome:path.join(home,'agents'),registry:{snapshot:async()=>({skills:[],complete:true})}});expect((await collect()).skills[0]).toMatchObject({name:'demo',modelInvocable:true,userInvocable:true});service.change(row.id,service.read().revision,'enabled',false);expect((await collect()).skills[0]).toMatchObject({modelInvocable:false,userInvocable:false});const restarted=new ManagedSkills(home,()=>[]);expect(restarted.read().skills[0].enabled).toBe(false);restarted.change(row.id,restarted.read().revision,'enabled',true);expect((await collect()).skills[0].modelInvocable).toBe(true)})
 it('updates, rolls back, removes and restores without deleting version resources',()=>{const {service}=fixture();let row=install(service);install(service,text('demo','Updated'));row=service.read().skills[0];expect(row.previous).toBeTruthy();service.change(row.id,service.read().revision,'rollback');expect(fs.readFileSync(path.join(row.root,row.name,'SKILL.md'),'utf8')).toContain('Use the template.');service.change(row.id,service.read().revision,'remove');expect(fs.existsSync(path.join(row.root,row.name))).toBe(false);service.change(row.id,service.read().revision,'restore');expect(service.read().skills[0].enabled).toBe(false);expect(fs.existsSync(path.join(row.root,row.name,'resources/template.txt'))).toBe(true)})
 it('retains explicit manual-only author policy across disable and enable',()=>{const {service}=fixture();const row=install(service,text().replace('description:','disable-model-invocation: true\ndescription:'));service.change(row.id,service.read().revision,'enabled',false);service.change(row.id,service.read().revision,'enabled',true);expect(service.read().skills[0].auto).toBe(false);expect(fs.readFileSync(path.join(row.root,row.name,'SKILL.md'),'utf8')).toContain('disable-model-invocation: true')})
 it('imports an exported ZIP into a clean receiver with all resources',()=>{const a=fixture(),b=fixture(),row=install(a.service),zip=a.service.export(row.id).bytes,p=b.service.inspect({scope:'global',zip:true,files:[{path:'demo.zip',data:zip.toString('base64')}]});b.service.commit(p.id,[{key:'SKILL.md',mode:'update'}],true);expect(b.service.read().skills).toHaveLength(1);expect(fs.existsSync(path.join(b.home,'skills/demo/resources/template.txt'))).toBe(true)})
 it('supports multi-skill selection and project isolation',()=>{const {service,project,home}=fixture(),p=service.inspect({scope:project,files:['one','two'].map(n=>({path:n+'/SKILL.md',data:Buffer.from(text(n)).toString('base64')}))});service.commit(p.id,[{key:'two/SKILL.md',mode:'update'}],true);expect(fs.existsSync(path.join(project,'.dsh/skills/two/SKILL.md'))).toBe(true);expect(fs.existsSync(path.join(home,'skills/two'))).toBe(false);expect(service.read().skills).toHaveLength(1)})
 it('rejects unknown projects, malformed metadata and traversal',()=>{const {service}=fixture();expect(()=>service.inspect({...payload(),scope:'C:/unrelated'})).toThrow();expect(()=>service.inspect({scope:'global',files:[{path:'../SKILL.md',data:''}]})).toThrow();const p=service.inspect(payload('no metadata'));expect(p.candidates[0].error).toBeTruthy();expect(()=>service.commit(p.id,[{key:p.candidates[0].key,mode:'update'}],true)).toThrow()})
 it('does not overwrite unmanaged skills or external edits',()=>{const {service,home}=fixture();fs.mkdirSync(path.join(home,'skills/demo'),{recursive:true});fs.writeFileSync(path.join(home,'skills/demo/SKILL.md'),text());const p=service.inspect(payload());expect(()=>service.commit(p.id,[{key:p.candidates[0].key,mode:'update'}],true)).toThrow('非本模块');service.commit(p.id,[{key:p.candidates[0].key,mode:'copy',name:'demo-copy'}],true);const row=service.read().skills[0];fs.appendFileSync(path.join(row.root,row.name,'SKILL.md'),'external edit');expect(()=>service.change(row.id,service.read().revision,'enabled',false)).toThrow('外部被修改');expect(service.read().skills[0].enabled).toBe(true)})
 it('rejects stale revisions and duplicated batch choices without partial installation',()=>{const {service}=fixture(),row=install(service);expect(()=>service.change(row.id,0,'remove')).toThrow('列表已改变');const p=service.inspect(payload(text('other')));expect(()=>service.commit(p.id,[{key:p.candidates[0].key,mode:'update'},{key:p.candidates[0].key,mode:'update'}],true)).toThrow();expect(service.read().skills).toHaveLength(1)})
 it('rejects ZIP path attacks through the shared bounded reader',()=>{const {service}=fixture();const zip=packageZip(new Map([['SKILL.md',Buffer.from(text())]]));zip[0]=0;expect(()=>service.inspect({scope:'global',zip:true,files:[{path:'bad.zip',data:zip.toString('base64')}]})).toThrow()})
})
