// @vitest-environment node
import {describe,it,expect} from 'vitest'
import {editPreset,lockedReason,exactOverride,presetConfiguredRows} from '../src/host/inventory-control.ts'
describe('inventory controls',()=>{
 it('does not allow plugin switches to rewrite published role presets',()=>{expect(presetConfiguredRows('- id: x\n  name: tool\n',[{entryId:'x',moduleName:'tool',enabled:true,fiberPhase:null}],'user','workbench-role-example-v1')[0].controlReason).toContain('岗位')})
 it('writes an include override by ID without changing a sibling from the same module',()=>{const result=exactOverride('- id: first\n  name: tool\n  config:\n    keep: yes\n','include:second','tool',false);expect(result).toContain('id: second');expect(result).toContain('keep: yes');expect(result.match(/disabled: true/g)).toHaveLength(1);expect(exactOverride(result,'include:second','tool',true)).toContain('disabled: false')})
 it('uses saved user preset state and makes system presets read-only',()=>{const rows=[{entryId:'x',moduleName:'tool',enabled:true,fiberPhase:null}];expect(presetConfiguredRows('- id: x\n  name: tool\n  disabled: true\n',rows,'user')[0].enabled).toBe(false);expect(presetConfiguredRows('- id: x\n  name: tool\n',rows,'system')[0].controlReason).toContain('只读');expect(lockedReason({entryId:'include:web-ui-task-board',moduleName:'@linxin666/dsh-web-all/task-board',enabled:true,fiberPhase:'active'})).toBeUndefined()})
 it('edits exactly the requested preset instance and preserves sibling configuration',()=>{const text='- id: first\n  name: tool\n  config:\n    path: keep-me\n- id: second\n  name: tool\n';const result=editPreset(text,'first','tool',false);expect(result).toContain('path: keep-me');expect(result.match(/disabled: true/g)).toHaveLength(1);expect(editPreset(result,'first','tool',true)).toContain('disabled: false')})
 it('rejects ambiguous entries and conditional enablement',()=>{expect(()=>editPreset('- id: x\n  name: tool\n- id: x\n  name: tool\n','x','tool',false)).toThrow('唯一');expect(()=>editPreset('- id: x\n  name: tool\n  disabled: !!js env.TEST\n','x','tool',false)).toThrow('表达式')})
 it('protects management and core service entries but allows ordinary extensions',()=>{expect(lockedReason({entryId:'web-ui-plugin-manager',moduleName:'pkg',enabled:true,fiberPhase:'active'})).toBeTruthy();expect(lockedReason({entryId:'anything',moduleName:'@deepseek-ai/dsh-host-webserver',enabled:true,fiberPhase:'active'})).toBeTruthy();expect(lockedReason({entryId:'ordinary',moduleName:'my-plugin',enabled:true,fiberPhase:'active'})).toBeUndefined()})
})
