import { PillCheckbox } from '../../../../shared/client/PillCheckbox.tsx'
import React,{useEffect,useRef,useState} from 'react'
import {EnableSwitch} from '../../../../shared/client/EnableSwitch.tsx'
import type {ManagedSkill} from '../managed.ts'
import css from './managed-panel.module.css'

const prefix='/api/dsh-skill-explorer/manage/'
async function request(action:string,body?:unknown){const response=await fetch(prefix+action,body===undefined?undefined:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error??'操作失败');return data}
interface Preview {id:string;candidates:{key:string;name:string;description:string;warnings:string[];error?:string;fileCount:number;existing:{id:string;hash:string}[]}[]}
interface Choice {key:string;mode:'copy'|'update';name?:string}
function SkillContents({id}:{id:string}){const [data,setData]=useState<{content:string;files:string[]}>(),[error,setError]=useState('');return <details onToggle={e=>{if(e.currentTarget.open&&!data)void request('detail?id='+encodeURIComponent(id)).then(setData).catch(e=>setError(String(e)))}}><summary>查看技能说明与资源文件</summary>{error&&<p role="alert">{error}</p>}{data&&<><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{data.content}</pre><ul>{data.files.map(file=><li key={file}>{file}</li>)}</ul></>}</details>}
export function ManagedPanel(){
 const [snapshot,setSnapshot]=useState<{revision:number;skills:ManagedSkill[];projects:string[]}>({revision:0,skills:[],projects:[]}),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[scope,setScope]=useState('global'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState<Preview>(),[choices,setChoices]=useState<Choice[]>([]),[enable,setEnable]=useState(true),[importing,setImporting]=useState(false)
 const lock=useRef(false),file=useRef<HTMLInputElement>(null),folder=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null)
 const reload=async()=>setSnapshot(await request('list'))
 useEffect(()=>{void reload().catch(e=>setError(String(e)))},[])
 useEffect(()=>{if(importing&&!dialog.current?.open)dialog.current?.showModal()},[importing])
 const run=async(action:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{lock.current=false;setBusy(false)}}
 const change=(row:ManagedSkill,action:string,value?:unknown)=>void run(async()=>{await request('change',{id:row.id,revision:snapshot.revision,action,value});await reload();setNotice(action==='enabled'?'已更新技能调用设置；已载入对话的说明不会撤回，正在执行的任务保持。':'操作已完成')})
 const upload=(files:FileList|null)=>{if(!files?.length)return;const entries=Array.from(files);void run(async()=>{
  if(entries.length>500||entries.reduce((n,f)=>n+f.size,0)>32*1024*1024)throw Error('最多 500 个文件、32 MiB')
  const payload=[];for(const item of entries){const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(item)});payload.push({path:item.webkitRelativePath||item.name,data})}
  const p:Preview=await request('inspect',{scope,files:payload,zip:entries.length===1&&entries[0].name.toLowerCase().endsWith('.zip')});setPreview(p);setChoices(p.candidates.filter(c=>!c.error).map(c=>({key:c.key,mode:'update'})))
 })}
 const close=()=>{if(busy)return;void run(async()=>{if(preview)await request('discard',{id:preview.id});setPreview(undefined);setChoices([]);setImporting(false)})}
 const groups=new Map<string,ManagedSkill[]>()
 for(const row of snapshot.skills){if((filter==='trash')!==!!row.removed)continue;if(filter==='enabled'&&!row.enabled||filter==='disabled'&&row.enabled||filter==='review'&&!row.warnings.length)continue;if(![row.name,row.description,row.category,row.scope].join(' ').toLowerCase().includes(query.toLowerCase()))continue;groups.set(row.category,[...(groups.get(row.category)??[]),row])}
 return <section className={css.panel} aria-label="Skills 技能管理"><header className={css.toolbar}><h2>Skills 技能</h2><button onClick={()=>{setNotice('');setImporting(true)}} disabled={busy}>导入 Skills</button><button disabled={busy} onClick={()=>void run(reload)}>刷新</button></header>
  <div className={css.toolbar}><input aria-label="搜索技能" placeholder="搜索名称、用途或分类" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="技能状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部</option><option value="enabled">已启用</option><option value="disabled">已停用</option><option value="review">待核对 / 适配</option><option value="trash">回收站</option></select></div>
  <p className={css.muted}>导入副本由工作台管理。启用表示允许调用；运行环境及执行结果需实际验证。</p>
  {error&&<p role="alert" className={css.error}>{error}</p>}{notice&&<p role="status">{notice}</p>}
  {!groups.size&&<p>暂无符合条件的技能。可导入包含 SKILL.md 的文件夹或 ZIP。</p>}
  {[...groups].map(([group,rows])=><section key={group}><h3>{group} · {rows.length}</h3><div className={css.grid}>{rows.map(row=><article className={css.card} key={row.id}><header><strong>{row.name}</strong><EnableSwitch checked={row.enabled} busy={busy} disabled={row.removed} label={(row.enabled?'停用':'启用')+'技能 '+row.name} onChange={value=>change(row,'enabled',value)}/></header><p>{row.description}</p><p className={css.muted}>{row.removed?'已移除':row.enabled?'已启用':'已停用'} · {row.scope==='global'?'全局':row.scope} · 本地导入</p>
   <details><summary>详情与配置</summary><p>版本摘要：{row.hash.slice(0,12)} · {row.updatedAt.slice(0,10)}</p><p>目录：{row.root}</p>{row.warnings.map(w=><p key={w}>{w}</p>)}<p>连接和执行状态：未在本页验证</p><SkillContents key={row.hash} id={row.id}/>
   {!row.removed&&<><label className={css.toolbar}>允许 AI 自动选用 <EnableSwitch label={'允许 AI 自动选用 '+row.name} checked={row.auto} busy={busy} onChange={v=>change(row,'auto',v)}/></label><label>分类 <input aria-label={'分类 '+row.name} defaultValue={row.category} key={row.category} onBlur={e=>{if(e.target.value.trim()&&e.target.value!==row.category)change(row,'category',e.target.value)}}/></label></>}
   <div className={css.toolbar}><a href={prefix+'export?id='+encodeURIComponent(row.id)} download={row.name+'.zip'}>导出</a>
   {row.removed?<button disabled={busy} onClick={()=>change(row,'restore')}>恢复（保持停用）</button>:<><button disabled={busy||!row.previous} onClick={()=>{if(window.confirm('回退到上一版本并停用？当前版本会保留。'))change(row,'rollback')}}>回退版本</button><button disabled={busy} onClick={()=>{if(window.confirm('移除 '+row.name+'？新的技能调用将停止，原始文件和历史对话保留，可从回收站恢复。'))change(row,'remove')}}>移除</button></>}</div></details>
  </article>)}</div></section>)}
  {importing&&<dialog ref={dialog} className={css.dialog} onCancel={e=>{e.preventDefault();e.stopPropagation();close()}} onKeyDown={e=>{if(e.key==='Escape')e.stopPropagation()}}><h3>导入 Skills</h3><p>支持 Codex 等常见 SKILL.md 格式；不会安装依赖或运行脚本。</p>
   {!preview?<><label>适用范围 <select value={scope} onChange={e=>setScope(e.target.value)} disabled={busy}><option value="global">工作台全局</option>{snapshot.projects.map(p=><option key={p} value={p}>{p}</option>)}</select></label><div className={css.toolbar}><button disabled={busy} onClick={()=>file.current?.click()}>选择 ZIP / SKILL.md</button><button disabled={busy} onClick={()=>folder.current?.click()}>选择文件夹</button></div><input ref={file} type="file" accept=".zip,.md" hidden onChange={e=>upload(e.target.files)}/><input ref={folder} type="file" multiple hidden {...{webkitdirectory:''} as any} onChange={e=>upload(e.target.files)}/></>:<><p>选择要导入的技能；更新会保留旧版本，已有技能开关保持。</p>{preview.candidates.map(c=>{const selected=choices.find(x=>x.key===c.key);return <div className={css.card} key={c.key}><label><PillCheckbox type="checkbox" disabled={!!c.error||busy} checked={!!selected} onChange={e=>setChoices(old=>e.target.checked?[...old,{key:c.key,mode:'update'}]:old.filter(x=>x.key!==c.key))}/>{c.name||c.key} · {c.fileCount} 个文件</label><p>{c.description}</p>{c.error&&<p role="alert">{c.error}</p>}{c.warnings.map(w=><p key={w}>{w}</p>)}{selected&&<><select aria-label={'导入方式 '+c.name} value={selected.mode} onChange={e=>setChoices(old=>old.map(x=>x.key===c.key?{...x,mode:e.target.value as Choice['mode']}:x))}><option value="update">{c.existing.length?'更新已有技能':'导入新技能'}</option><option value="copy">另存副本</option></select>{selected.mode==='copy'&&<input aria-label={'副本名称 '+c.name} placeholder="新的英文名称" value={selected.name??''} onChange={e=>setChoices(old=>old.map(x=>x.key===c.key?{...x,name:e.target.value}:x))}/>}</>}</div>})}<label><PillCheckbox type="checkbox" checked={enable} onChange={e=>setEnable(e.target.checked)}/>新技能导入后启用</label></>}
   {error&&<p role="alert" className={css.error}>{error}</p>}<footer className={css.toolbar}><button disabled={busy} onClick={close}>取消</button>{preview&&<button disabled={busy||!choices.length} onClick={()=>void run(async()=>{const r=await request('commit',{id:preview.id,choices,enabled:enable});setPreview(undefined);setImporting(false);await reload();setNotice('已导入 '+r.count+' 个技能'+(r.unchanged?'，'+r.unchanged+' 个相同版本已跳过':'')+'；实际调用兼容性仍需验证。')})}>{busy?'处理中…':'确认导入'}</button>}</footer>
  </dialog>}
 </section>
}
