import React,{useEffect,useRef,useState} from 'react'
import {EnableSwitch} from '../../../../shared/client/EnableSwitch.tsx'
import {SkillApi,type SkillEntry} from './api.ts'
import {ManagementRow} from '../../../../shared/client/ManagementRow.tsx'
import {openWorkbenchLink} from '../../../dsh-plugin-manager/src/client/workbench-navigation.ts'
import s from '../../../dsh-client-ui-plain-chat/src/client/ManagedCapabilities.module.css'
export function OtherSkills(){const [rows,setRows]=useState<(SkillEntry&{source:string})[]>([]),[selected,setSelected]=useState<SkillEntry&{source:string}>(),[error,setError]=useState(''),[query,setQuery]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),lock=useRef(false)
 useEffect(()=>{let active=true;void new SkillApi().list().then(d=>{if(active){setRows(d.groups.flatMap(g=>g.skills.map(skill=>({...skill,source:g.title}))));setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 const toggle=async()=>{if(!selected?.path||lock.current)return;lock.current=true;setBusy(true);setError('');try{await new SkillApi().setEnabled(selected.name,selected.path,!selected.modelInvocable);const next={...selected,modelInvocable:!selected.modelInvocable};setSelected(next);setRows(rows=>rows.map(r=>r.path===next.path?next:r))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{lock.current=false;setBusy(false)}}
 return <>{error&&<p role="alert" className={s.error}>{error}</p>}{selected?<><button className={s.button} onClick={()=>setSelected(undefined)}>← 其他来源列表</button><h2>{selected.name}</h2><p>{selected.description}</p><p className={s.muted}>来源：{selected.source}</p><p className={s.muted}>位置：{selected.path??selected.provider??'由来源提供'}</p>{selected.path?<label className={s.check}>允许 AI 自动选用 <EnableSwitch checked={selected.modelInvocable} busy={busy} label={'允许 AI 自动选用 '+selected.name} onChange={()=>void toggle()}/></label>:<p>此技能由来源管理，此处仅供查看。</p>}{selected.provider&&selected.provider!=='filesystem'&&<button className={s.button} onClick={()=>openWorkbenchLink({section:'plugins'})}>打开插件管理 ↗</button>}</>:<><input className={s.search} aria-label="搜索其他来源技能" placeholder="搜索名称或用途" value={query} onChange={e=>setQuery(e.target.value)}/><div className={s.capabilityList}>{rows.filter(r=>(r.name+' '+r.description).toLowerCase().includes(query.toLowerCase())).map((r,i)=><ManagementRow key={r.path??r.name+i} name={r.name} description={r.description} status="来源管理" statusHint={r.source} openLabel={'查看其他来源技能：'+r.name} onOpen={()=>setSelected(r)}/>)}</div>{loaded&&!rows.length&&<p className={s.empty}>暂无其他来源技能。</p>}</>}</>
}
