import css from './managed-panel.module.css'
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react'
import type {ManagedSkill} from '../managed.ts'
import {ManagementRow} from '../../../../shared/client/ManagementRow.tsx'
import {Modal} from '../../../dsh-client-ui-plain-chat/src/client/PreviewModal.tsx'
import {SkillDetail} from './SkillDetail.tsx'
import {OtherSkills} from './OtherSkills.tsx'
import {managedRequest as request,prefix} from './managed-api.ts'
import {pendingNavigation,consumeNavigation,restoredFrame,useNavigationFrame} from '../../../dsh-plugin-manager/src/client/workbench-navigation.ts'
import s from '../../../dsh-client-ui-plain-chat/src/client/ManagedCapabilities.module.css'
type Snapshot={revision:number;skills:ManagedSkill[];projects:string[]}
type View={query:string;filter:string;status:string;category:string;scope:string;page:'list'|'trash'|'other';selected:string|null;tab:string}
const defaults:View={query:'',filter:'all',status:'all',category:'',scope:'',page:'list',selected:null,tab:'settings'}
function initial():View{try{return {...defaults,...JSON.parse(sessionStorage.getItem('skills-center-view')??'{}'),...restoredFrame(pendingNavigation('skills')?.restore,'skills')?.view}}catch{return defaults}}
export function SkillsCenter({snapshot,busy,error,onImport,reload,change}:{snapshot:Snapshot;busy:boolean;error:string;onImport:()=>void;reload:()=>void;change:(row:ManagedSkill,action:string,value?:unknown)=>void}){
 const [view,setView]=useState(initial),[filtering,setFiltering]=useState(false),[exporting,setExporting]=useState(false),[confirm,setConfirm]=useState<'remove'>(),[managingTags,setManagingTags]=useState(false),[tagFrom,setTagFrom]=useState(''),[tagTo,setTagTo]=useState(''),[tagError,setTagError]=useState(''),[tagBusy,setTagBusy]=useState(false),listPreferences=useRef<View>(),listScroll=useRef(0),root=useRef<HTMLElement>(null)
 const update=(patch:Partial<View>)=>setView(v=>({...v,...patch})),row=snapshot.skills.find(r=>r.id===view.selected)
 useEffect(()=>{try{sessionStorage.setItem('skills-center-view',JSON.stringify(view))}catch{}},[view])
 useEffect(()=>{const link=pendingNavigation('skills');consumeNavigation(link);const go=(e:Event)=>{const l=(e as CustomEvent).detail;if(l?.section==='skills'){const saved=restoredFrame(l.restore,'skills')?.view;if(saved)setView({...defaults,...saved});consumeNavigation(l)}};window.addEventListener('workbench-capability-link',go);return()=>window.removeEventListener('workbench-capability-link',go)},[])
 useNavigationFrame('skills',5,()=>({section:'skills',label:'Skills 技能',view}))
 function scroller(){let el=root.current?.parentElement;while(el&&el.scrollHeight<=el.clientHeight)el=el.parentElement;return el}
 const open=(id:string)=>{listScroll.current=scroller()?.scrollTop??0;update({selected:id,tab:'settings'})}
 useLayoutEffect(()=>{if(!view.selected){const el=scroller();if(el)el.scrollTop=listScroll.current}},[view.selected])
 const tags=[...new Set(snapshot.skills.flatMap(r=>r.tags??(r.category&&r.category!=='未分类'?[r.category]:[])))].sort();
 const tagAction=async(remove:boolean)=>{if(tagBusy)return;setTagBusy(true);setTagError('');try{await request('tags',{revision:snapshot.revision,from:tagFrom,...remove?{}:{to:tagTo}});reload();setTagFrom('');setTagTo('')}catch(e){setTagError(e instanceof Error?e.message:String(e))}finally{setTagBusy(false)}};
 const visible=snapshot.skills.filter(r=>!!r.removed===(view.page==='trash')&&(view.filter!=='pinned'||r.pinned)&&(view.status!=='enabled'||r.enabled)&&(view.status!=='disabled'||!r.enabled)&&(!view.category||(r.tags??(r.category==='未分类'?[]:[r.category])).includes(view.category))&&(!view.scope||(r.usage??'legacy')===view.scope)&&[r.name,r.description,...r.tags??[r.category]].join(' ').toLowerCase().includes(view.query.toLowerCase())).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned))
 return <section ref={root} className={s.page} aria-label="Skills 技能管理">
 {row?<button className={`${s.button} ${s.detailBack}`} onClick={()=>update({selected:null})}>← {view.page==='trash'?'返回回收站':'全部技能'}</button>:<div className={s.heading}><h2>{view.page==='list'?'Skills 技能':view.page==='trash'?'技能回收站':'其他来源技能'}</h2>{view.page==='list'?<div className={s.actions}><button className={`${s.button} ${s.primary}`} onClick={onImport} disabled={busy}>导入技能</button><button className={s.button} onClick={()=>setExporting(true)} disabled={busy||!snapshot.skills.length}>导出技能</button><button className={s.iconButton} disabled={busy} aria-label="刷新技能" title="刷新技能" onClick={reload}>↻</button></div>:<button className={s.button} onClick={()=>setView(listPreferences.current??{...defaults})}>← 全部技能</button>}</div>}
 {error&&<p role="alert" className={s.error}>{error}</p>}
 {row?<SkillDetail row={row} tags={tags} tab={view.tab} onTab={tab=>update({tab})} busy={busy} change={change} onConfirm={setConfirm}/>:view.page==='other'?<OtherSkills/>:<>
 <input className={s.search} aria-label="搜索技能" placeholder="搜索技能名称、用途或标签" value={view.query} onChange={e=>update({query:e.target.value})}/>
 <div className={s.listToolbar}><div className={s.tabs} aria-label="技能列表">{[['all','全部'],['pinned','收藏']].map(([value,label])=><button key={value} aria-pressed={view.filter===value} onClick={()=>update({filter:value})}>{label}</button>)}</div><button className={s.button} aria-expanded={filtering} onClick={()=>setFiltering(!filtering)}>筛选{view.category||view.scope||['enabled','disabled'].includes(view.status)?' · 已启用':''}</button></div>
 {filtering&&<div className={s.filterPanel}><label className={s.field}>状态<select aria-label="技能状态筛选" value={view.status} onChange={e=>update({status:e.target.value})}><option value="all">全部</option><option value="enabled">已启用</option><option value="disabled">已停用</option></select></label><label className={s.field}>标签<select aria-label="技能标签筛选" value={view.category} onChange={e=>update({category:e.target.value})}><option value="">全部标签</option>{tags.map(v=><option key={v}>{v}</option>)}</select></label><label className={s.field}>适用范围<select aria-label="技能范围筛选" value={view.scope} onChange={e=>update({scope:e.target.value})}><option value="">全部范围</option><option value="all">全部对话</option><option value="roles">指定岗位</option><option value="legacy">保留原有范围</option></select></label><button className={s.button} onClick={()=>update({filter:'all',status:'all',category:'',scope:'',query:''})}>清除筛选</button></div>}
 <div className={s.capabilityList}>{visible.map(r=><div key={r.id}><ManagementRow key={r.id} name={r.name} description={r.description} status={r.removed?'已移除':r.enabled?'已启用':'已停用'} onOpen={()=>open(r.id)} openLabel={'管理技能：'+r.name} pinned={r.pinned} busy={busy} onPin={r.removed?undefined:()=>change(r,'pinned',!r.pinned)} pinLabel={(r.pinned?'取消收藏':'收藏技能')+'：'+r.name} attributes={{'data-managed-skill':r.id}}/><div className={css.tags}>{(r.tags??[]).slice(0,2).map(t=><button className={css.tag} key={t} onClick={()=>update({category:t})}>{t}</button>)}{(r.tags?.length??0)>2&&<span>＋{r.tags!.length-2}</span>}</div></div>)}</div>
 {!visible.length&&<div className={s.empty}><p>{view.page==='trash'?'回收站为空。':view.filter==='pinned'?'暂无符合条件的收藏技能。':'暂无符合条件的技能。'}</p>{view.query||view.category||view.scope?<button className={s.button} onClick={()=>update({query:'',category:'',scope:'',filter:'all'})}>清空搜索和筛选</button>:view.page==='list'&&view.filter==='all'?<button className={s.button} onClick={onImport}>导入技能</button>:null}</div>}
 {view.page==='list'&&<div className={s.actions}><button className={s.button} onClick={()=>setManagingTags(true)}>管理标签</button><button className={s.button} onClick={()=>{listPreferences.current=view;update({page:'other'})}}>其他来源技能</button><button className={s.button} onClick={()=>{listPreferences.current=view;update({page:'trash',filter:'all',status:'all',category:'',scope:'',query:''})}}>回收站</button></div>}
 </>}
 {managingTags&&<Modal title="管理标签" closeLabel="关闭标签管理" onClose={()=>{if(!tagBusy)setManagingTags(false)}}><div className={s.page}><p>重命名会更新所有技能上的同名标签；删除仅移除标签，不删除技能。</p><label className={s.field}>标签<select aria-label="要管理的标签" value={tagFrom} onChange={e=>{setTagFrom(e.target.value);setTagTo(e.target.value)}}><option value="">选择标签</option>{tags.map(t=><option key={t}>{t}</option>)}</select></label><input aria-label="标签新名称" value={tagTo} maxLength={40} onChange={e=>setTagTo(e.target.value)}/><button className={s.button} disabled={tagBusy||!tagFrom||!tagTo.trim()} onClick={()=>void tagAction(false)}>重命名标签</button><button className={s.button} disabled={tagBusy||!tagFrom} onClick={()=>void tagAction(true)}>删除标签</button>{tagError&&<p role="alert">{tagError}</p>}</div></Modal>}
 {exporting&&<Modal title="导出技能" closeLabel="关闭导出" onClose={()=>setExporting(false)}><div className={`${s.page} ${s.dialogBody}`}><p>选择一个技能，导出包含说明与资源文件的 ZIP。</p>{snapshot.skills.map(r=><p key={r.id}><a className={s.button} href={prefix+'export?id='+encodeURIComponent(r.id)} download={r.name+'.zip'} onClick={()=>setExporting(false)}>{r.name}{r.removed?' · 已移除':''}</a></p>)}</div></Modal>}
 {confirm&&row&&<Modal title={'移除技能'} closeLabel="取消操作" onClose={()=>{if(!busy)setConfirm(undefined)}}><div className={`${s.page} ${s.dialogBody}`}><p>{'新的技能调用将停止，可从回收站恢复。'}</p>{error&&<p role="alert" className={s.error}>{error}</p>}<div className={s.actions}><button className={s.button} disabled={busy} onClick={()=>setConfirm(undefined)}>取消</button><button className={`${s.button} ${s.primary}`} disabled={busy} onClick={()=>{change(row,confirm);setConfirm(undefined)}}>确认{'移除'}</button></div></div></Modal>}
 </section>
}
