export const capabilityZh = {
  capHideLibrary: '收起能力库', capShowLibrary: '展开能力库', capHideSettings: '收起配件设置', capShowSettings: '展开配件设置',
  capResizeHint: '拖动调整宽度，向外拖到底可收起', capRestoreHint: '点击或向内拖动恢复', capAlreadyAdded: '此配件已添加：',
  capLibrary: '能力配件库', capLibraryHint: '拖入助手，组合它的工作能力', capSearch: '搜索配件',
  capAll: '全部', capWeb: '网页', capOffice: '办公', capData: '资料', capCount: '款示例配件',
  capBrowser: '浏览器操作', capBrowserDesc: '浏览网页、读取信息、填写表单',
  capDocuments: '文档处理', capDocumentsDesc: '整理内容，撰写报告与工作文档',
  capSheets: '表格处理', capSheetsDesc: '整理数据，分析与汇总表格',
  capKnowledge: '知识库', capKnowledgeDesc: '查阅资料，为回答补充依据',
  capFiles: '本地文件', capFilesDesc: '查找文件，整理工作目录',
  capMail: '邮件协作', capMailDesc: '整理来信，准备邮件草稿',
  capAdd: '添加', capAdded: '已添加', capRemove: '移除', capInspect: '查看配件设置',
  capNoResults: '没有找到相关配件', capClear: '清空筛选', capExample: '示例',
  capCanvas: '助手配置', capIdentity: '岗位信息', capAdvanced: '工作要求与输出格式',
  capAttached: '已添加的能力', capAttachedHint: '点击配件卡片，在右侧调整设置。',
  capDrop: '将配件拖到这里', capDropHint: '也可以点击左侧配件的“添加”按钮',
  capDropMore: '拖入更多配件', capEmpty: '还没有添加能力配件',
  capSettings: '配件设置', capOverview: '配置预览', capEnabled: '启用此能力',
  capEnableHint: '仅调整本次预览中的开关状态', capActive: '已启用', capPaused: '已停用',
  capNotAdded: '尚未添加到此助手', capProvider: '提供方', capStatus: '连接状态', capNotConnected: '未连接 · 界面演示',
  capBrowserChoice: '使用的浏览器', capAccess: '访问范围', capAnySite: '所有网站', capSpecificSite: '指定网站',
  capSites: '允许访问的网站', capSitesPlaceholder: '每行一个域名，例如 example.com',
  capActions: '允许的操作', capRead: '读取网页', capFill: '填写表单', capSubmit: '提交操作',
  capConfirm: '提交前由我确认', capConfirmHint: '权限设置仅作展示，尚未用于实际操作。',
  capOutput: '输出形式', capDocOutput: '工作报告', capSheetOutput: '汇总表格', capMailOutput: '邮件草稿',
  capSource: '资料来源', capSourcePlaceholder: '例如：项目资料、产品手册',
  capFolder: '工作目录', capFolderPlaceholder: '例如：项目资料 / 输出',
  capReview: '完成后由我检查', capReviewHint: '设置助手交付结果时的检查方式',
  capGuide: '先选择一个配件', capGuideHint: '从能力库添加配件，或点击已添加的能力卡片。',
  capBoundary: '仅预览 · 不安装插件、不连接浏览器，关闭后不保留配置',
  capFooter: '组合职责与能力，预览你的岗位助手。', capAbilitySummary: '能力组合',
  capAddAnnouncement: '已添加配件：', capRemoveAnnouncement: '已移除配件：',
  capDemoNote: '配件目录为示例，尚未读取已安装插件。', capColorDetails: '外观与配色',
}

export const capabilityEn: Record<keyof typeof capabilityZh, string> = {
  capHideLibrary: 'Hide capability library', capShowLibrary: 'Show capability library', capHideSettings: 'Hide capability settings', capShowSettings: 'Show capability settings',
  capResizeHint: 'Drag to resize; drag outward to collapse', capRestoreHint: 'Click or drag inward to restore', capAlreadyAdded: 'Already added: ',
  capLibrary: 'Capability library', capLibraryHint: 'Drag capabilities into your assistant', capSearch: 'Search capabilities',
  capAll: 'All', capWeb: 'Web', capOffice: 'Office', capData: 'Knowledge', capCount: 'example capabilities',
  capBrowser: 'Browser', capBrowserDesc: 'Browse pages, read information and fill forms',
  capDocuments: 'Documents', capDocumentsDesc: 'Organize content and draft work reports',
  capSheets: 'Spreadsheets', capSheetsDesc: 'Organize, analyze and summarize data',
  capKnowledge: 'Knowledge base', capKnowledgeDesc: 'Find reference material for your answers',
  capFiles: 'Local files', capFilesDesc: 'Find files and organize working folders',
  capMail: 'Email', capMailDesc: 'Review incoming mail and prepare drafts',
  capAdd: 'Add', capAdded: 'Added', capRemove: 'Remove', capInspect: 'Inspect capability',
  capNoResults: 'No matching capabilities', capClear: 'Clear filters', capExample: 'Example',
  capCanvas: 'Assistant setup', capIdentity: 'Role information', capAdvanced: 'Requirements and output format',
  capAttached: 'Attached capabilities', capAttachedHint: 'Select a card to adjust its settings on the right.',
  capDrop: 'Drop capabilities here', capDropHint: 'Or use the Add button in the library',
  capDropMore: 'Drop another capability', capEmpty: 'No capabilities added yet',
  capSettings: 'Capability settings', capOverview: 'Configuration preview', capEnabled: 'Enable capability',
  capEnableHint: 'Changes this preview only', capActive: 'Enabled', capPaused: 'Disabled',
  capNotAdded: 'Not attached to this assistant', capProvider: 'Provider', capStatus: 'Connection', capNotConnected: 'Not connected · Demo',
  capBrowserChoice: 'Browser', capAccess: 'Website access', capAnySite: 'All websites', capSpecificSite: 'Specific websites',
  capSites: 'Allowed websites', capSitesPlaceholder: 'One domain per line, e.g. example.com',
  capActions: 'Allowed actions', capRead: 'Read pages', capFill: 'Fill forms', capSubmit: 'Submit actions',
  capConfirm: 'Ask me before submitting', capConfirmHint: 'Permission controls are a preview and are not enforced yet.',
  capOutput: 'Output type', capDocOutput: 'Work report', capSheetOutput: 'Summary table', capMailOutput: 'Email draft',
  capSource: 'Reference sources', capSourcePlaceholder: 'e.g. Project materials, product manuals',
  capFolder: 'Working folder', capFolderPlaceholder: 'e.g. Project materials / Output',
  capReview: 'Let me review the result', capReviewHint: 'Choose how the assistant hands over its work',
  capGuide: 'Choose a capability', capGuideHint: 'Add an item from the library or select an attached card.',
  capBoundary: 'Preview only · No installation or browser connection. Closing discards changes.',
  capFooter: 'Combine a role and capabilities to preview your assistant.', capAbilitySummary: 'Capability mix',
  capAddAnnouncement: 'Capability added: ', capRemoveAnnouncement: 'Capability removed: ',
  capDemoNote: 'Example catalog. Installed plugins are not queried.', capColorDetails: 'Appearance and color',
}
