export const centerZh = {
  centerTitle: '能力中心', centerSubtitle: '把能力整理好，再交给合适的岗位。', centerManage: '管理能力', centerOpen: '在能力中心编辑',
  centerBoundary: 'UI 预览 · 目录与岗位关系为示例；编辑仅在本页暂存，刷新后重置。',
  centerSearch: '搜索能力、用途或来源', centerAll: '全部能力', centerPinned: '常用', centerPending: '待配置', centerUnused: '未被使用',
  centerPin: '设为常用', centerUnpin: '取消常用', centerConfigure: '配置能力', centerViewRoles: '查看使用岗位', centerExampleRoles: '个示例岗位',
  centerBack: '返回能力列表', centerBackRole: '返回岗位编辑', centerOverview: '概览与连接', centerInstructions: '使用说明', centerDefaults: '默认配置', centerRoles: '使用岗位',
  centerConnection: '尚未连接', centerConnectionHint: '接入后可在这里查看连接状态。当前可以先预览能力配置。', centerConnect: '连接功能待接入',
  centerGuide: '能力说明与操作规则', centerGuideHint: '描述能力如何工作、适合哪些任务，以及需要遵循的规则。',
  centerGuideExample: '先确认任务目标与可操作范围；完成后整理结果，涉及提交或修改的操作先请用户确认。',
  centerDefaultsHint: '这里编辑能力的默认值预览。岗位已有配置保持独立，实际继承与保存将在后续接入。',
  centerRoleSettings: '当前岗位设置', centerRoleSettingsHint: '仅用于本次岗位预览，不修改能力中心的默认值。',
  centerRoleHint: '以下来自内置岗位示例，用于预览引用关系；不是实际保存的岗位配置。', centerPreviewRole: '预览岗位',
  centerNoRoles: '暂未被示例岗位使用', centerNoRolesHint: '创建岗位助手时，可以从能力配件库添加这项能力。',
  centerTechnical: '技术信息', centerIdentity: '能力标识', centerVersion: '接入后显示', centerImplementation: '示例来源', centerEmpty: '这个筛选下还没有能力',
  centerEmptyHint: '试试其他筛选，或清空搜索词。', centerDraftHint: '编辑已暂存于当前页面 · 尚未写入配置', centerReturnCurrent: '返回当前岗位', centerCurrentRole: '当前编辑',
}
export const centerEn: Record<keyof typeof centerZh, string> = {
  centerTitle: 'Capability center', centerSubtitle: 'Organize capabilities and put them to work in the right roles.', centerManage: 'Manage capabilities', centerOpen: 'Edit in capability center',
  centerBoundary: 'UI preview · Example catalog and role links. Edits stay on this page and reset on reload.',
  centerSearch: 'Search capabilities, uses or providers', centerAll: 'All capabilities', centerPinned: 'Favorites', centerPending: 'Needs setup', centerUnused: 'Unused',
  centerPin: 'Add to favorites', centerUnpin: 'Remove from favorites', centerConfigure: 'Configure', centerViewRoles: 'View roles', centerExampleRoles: 'example roles',
  centerBack: 'Back to capabilities', centerBackRole: 'Back to role editor', centerOverview: 'Overview & connection', centerInstructions: 'Instructions', centerDefaults: 'Defaults', centerRoles: 'Roles',
  centerConnection: 'Not connected', centerConnectionHint: 'Connection status will appear here after integration. You can preview the settings now.', centerConnect: 'Connection coming later',
  centerGuide: 'Capability instructions and rules', centerGuideHint: 'Describe how this capability works, suitable tasks and the rules to follow.',
  centerGuideExample: 'Confirm the task and permitted scope first. Summarize results when finished and ask before submitting or changing anything.',
  centerDefaultsHint: 'Preview capability defaults here. Existing role settings stay independent; inheritance and saving will be added later.',
  centerRoleSettings: 'Settings for this role', centerRoleSettingsHint: 'Applies to this role preview only; capability defaults stay unchanged.',
  centerRoleHint: 'These links come from built-in role examples, not saved role configurations.', centerPreviewRole: 'Preview role',
  centerNoRoles: 'No example roles use this yet', centerNoRolesHint: 'Add this capability from the library when creating a role assistant.',
  centerTechnical: 'Technical information', centerIdentity: 'Capability ID', centerVersion: 'Available after integration', centerImplementation: 'Example provider', centerEmpty: 'No capabilities in this view',
  centerEmptyHint: 'Try a different filter or clear your search.', centerDraftHint: 'Edits held on this page · Not saved to configuration', centerReturnCurrent: 'Return to current role', centerCurrentRole: 'Editing now',
}
