import React, { useEffect, useState } from 'react'
import { actionNames, actionsOf, browserPackage, components, emptyDefinition, latest, references, type Action, type Definition, type Snapshot } from '../../../dsh-capabilities/src/core/model.ts'
import { issues } from '../../../dsh-capabilities/src/core/validation.ts'
import { capabilityClient, editorDrafts, lastCapabilityLink, openCapabilityLink, useCapabilities, type CapabilityLink } from './capability-client.ts'
import { ManagedWorkbench, CapabilityGlyph } from './ManagedWorkbench.tsx'
import { Modal } from './PreviewModal.tsx'
import { ManagedRoleEditor } from './ManagedRoles.tsx'
import s from './ManagedCapabilities.module.css'

export function ActionFields({ value, available = ['navigate', 'read', 'screenshot'], onChange }: { value: Action[]; available?: readonly Action[]; onChange: (value: Action[]) => void }) {
  return <div>{(['navigate', 'read', 'screenshot'] as const).map(action => <label key={action} className={s.check}><input type="checkbox" disabled={!available.includes(action)} checked={value.includes(action)} onChange={e => onChange(e.target.checked ? [...value, action] : value.filter(a => a !== action))}/>{actionNames[action]}</label>)}</div>
}
export function CapabilityEditor({ id, data, onClose, onSaved }: { id?: string; data: Snapshot; onClose: () => void; onSaved: (id: string) => void }) {
  const cap = data.state.capabilities.find(c => c.id === id), key = `capability:${id ?? 'new'}`
  const cached = editorDrafts.get(key)
  const [draft, setDraft] = useState<Definition>(() => structuredClone(cached?.value as Definition ?? cap?.draft ?? emptyDefinition()))
  const [revision, setRevision] = useState(cached?.revision ?? data.state.revision)
  const [selected, setSelected] = useState<string | null>(draft.components[0]?.componentId ?? null)
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [review, setReview] = useState(false), [applyRoles, setApplyRoles] = useState<string[]>([])
  const change = (next: Definition) => { setDraft(next); editorDrafts.set(key, { value: structuredClone(next), revision }) }
  const part = draft.components.find(p => p.componentId === selected), descriptor = components.find(c => c.id === selected)
  const linked = data.state.roles.filter(r => latest(r.versions)?.capabilities.some(b => b.capabilityId === id))
  const save = async (publish: boolean) => {
    setBusy(true); setMessage('')
    try { const result = await capabilityClient.command({ type: 'capability.save', id, definition: draft, publish, applyToRoles: publish ? applyRoles : [] }, revision); editorDrafts.delete(key); onSaved(result); onClose() }
    catch (error) { setMessage(String(error instanceof Error ? error.message : error)) }
    finally { setBusy(false) }
  }
  return <Modal title={id ? '编辑能力' : '创建能力'} closeLabel="关闭编辑器" onClose={onClose} wide><div className={s.page} style={{ display: 'contents' }}>
    <ManagedWorkbench libraryTitle="组件库" title="能力信息" library={components.map(c => ({ id: c.id, name: c.name, subtitle: `BrowserSkill · ${c.version}` }))} selected={selected} onSelect={setSelected}
      attached={draft.components.map(c => ({ id: c.componentId, name: components.find(i => i.id === c.componentId)?.name ?? c.componentId, subtitle: c.actions.map(a => actionNames[a]).join(' · ') || '未选择动作' }))}
      onAdd={componentId => { if (!draft.components.some(p => p.componentId === componentId)) change({ ...draft, components: [...draft.components, { componentId, actions: ['navigate', 'read', 'screenshot'] }] }); setSelected(componentId) }}
      onRemove={componentId => change({ ...draft, components: draft.components.filter(p => p.componentId !== componentId) })}
      form={<div className={s.fields}><label className={s.field}>能力名称<input value={draft.name} maxLength={80} placeholder="例如：网页资料采集" onChange={e => change({ ...draft, name: e.target.value })}/></label><label className={s.field}>简介<textarea rows={2} maxLength={1000} value={draft.description} onChange={e => change({ ...draft, description: e.target.value })}/></label><label className={s.field}>使用说明<textarea rows={6} maxLength={8000} value={draft.instructions} onChange={e => change({ ...draft, instructions: e.target.value })}/></label>{cap && <label className={s.field}>从历史版本恢复到当前草稿<select value="" onChange={e => { const value = cap.versions.find(v => v.version === Number(e.target.value)); if (value) change(structuredClone(value)) }}><option value="">选择版本…</option>{cap.versions.map(v => <option key={v.version} value={v.version}>v{v.version} · {v.createdAt.slice(0, 16).replace('T', ' ')}</option>)}</select></label>}</div>}
      inspector={descriptor ? <><h3>{descriptor.name}</h3><p className={s.muted}>选择此能力允许使用的业务动作。组件顺序不代表执行顺序。</p>{part ? <ActionFields value={part.actions} onChange={actions => change({ ...draft, components: draft.components.map(p => p.componentId === selected ? { ...p, actions } : p) })}/> : <p>请先将组件添加到中间区域。</p>}<h4>自动关联的支持组件</h4><ul className={s.list}>{descriptor.dependencies.map(dep => <li key={dep}>{dep.replace('@deepseek-ai/dsh-', '')}</li>)}</ul><p className={s.muted}>必需依赖由组件自动推导。移除业务组件后引用才会解除。</p><p className={s.notice}>{data.health.message}</p><p className={s.muted}>缺少运行环境时仍可保存；执行时会检查连接。</p></> : <p className={s.empty}>选择一个组件以调整动作。</p>}/>
    <div className={s.footer}><div>{message ? <p role="alert" className={s.error}>{message}</p> : <p>{issues(draft).join('；') || '已选择受支持的动作。发布前可检查影响范围。'}</p>}{revision !== data.state.revision && <button className={s.button} onClick={() => { setRevision(data.state.revision); setMessage('已更新基准，请核对保留的草稿后保存。') }}>保留草稿并更新保存基准</button>}</div><div className={s.actions}><button className={s.button} disabled={busy} onClick={() => void save(false)}>保存草稿</button><button className={`${s.button} ${s.primary}`} disabled={busy || !draft.name.trim() || issues(draft).length > 0} onClick={() => setReview(true)}>检查并发布</button></div></div>
    {review && <Modal title="发布新版本" closeLabel="返回编辑" onClose={() => setReview(false)}><div className={`${s.page} ${s.dialogBody}`}><p>当前发布：v{latest(cap?.versions ?? [])?.version ?? 0} → v{(latest(cap?.versions ?? [])?.version ?? 0) + 1}</p><p>原动作：{actionsOf(latest(cap?.versions ?? [])).map(a => actionNames[a]).join('、') || '无'}</p><p>新动作：{actionsOf(draft).map(a => actionNames[a]).join('、') || '无'}</p><p className={s.notice}>新增动作仅由新版本采用。移除动作会立即限制引用此能力的旧会话，并停止正在使用它的浏览器任务。</p><h4>让以下岗位的新会话采用此版本</h4>{linked.map(role => <label className={s.check} key={role.id}><input type="checkbox" checked={applyRoles.includes(role.id)} onChange={e => setApplyRoles(e.target.checked ? [...applyRoles, role.id] : applyRoles.filter(id => id !== role.id))}/>{role.draft.name}</label>)}{!linked.length && <p className={s.muted}>尚无引用此能力的已发布岗位。</p>}<button className={`${s.button} ${s.primary}`} disabled={busy} onClick={() => void save(true)}>{busy ? '发布中…' : '发布本地版本'}</button>{message && <p role="alert" className={s.error}>{message}</p>}</div></Modal>}
  </div></Modal>
}

function ComponentRelations({ data, capabilityId }: { data: Snapshot; capabilityId: string }) {
  const cap = data.state.capabilities.find(c => c.id === capabilityId)!
  return <>{cap.draft.components.map(part => { const descriptor = components.find(c => c.id === part.componentId)!, refs = references(data.state, descriptor.id, data.tasks)
    return <div key={part.componentId}><h4>业务插件</h4><div className={s.row}><div><strong>{descriptor.name}</strong><small>{browserPackage} · 固定版本 {descriptor.version}</small><small>{data.health.installed ? '已安装' : '未安装'} · {data.health.loaded ? '已由岗位适配层加载' : '未加载'}</small></div><button className={s.button} onClick={() => openCapabilityLink({ section: 'plugins', moduleName: '@linxin666/dsh-capabilities/browser', capabilityId })}>插件管理 ↗</button></div><p className={s.muted}>共关联 {refs.capabilities.length} 个能力、{refs.roles.length} 个岗位；活动会话 {refs.tasks.length} 个。底层插件安装一份，由各能力复用。</p><h4>共享支持服务</h4>{descriptor.dependencies.filter(dep => dep.startsWith('@')).map(dep => <div className={s.row} key={dep}><div><strong>{dep.replace('@deepseek-ai/dsh-', '')}</strong><small>{dep} · 必需依赖</small><small>{(() => { const status = data.dependencies?.find(d => d.id === dep); return !status ? '尚未检测' : `${status.version ?? '版本未知'} · ${status.pendingRestart ? '待重启' : status.loaded ? '已加载' : status.installed ? '已安装，未加载' : '未安装'}` })()}</small></div><button className={s.button} onClick={() => openCapabilityLink({ section: 'plugins', moduleName: dep, capabilityId })}>查看组件 ↗</button></div>)}<h4>浏览器环境</h4><div className={s.row}><div><strong>本机 CLI 与浏览器扩展</strong><small>{data.health.cliVersion ?? 'CLI 版本待检测'} · 扩展通过浏览器单独安装</small><small>{data.health.message}</small></div></div></div>
  })}{!cap.draft.components.length && <p>当前草稿没有组件。</p>}</>
}

export function ManagedCenter({ initialId, embedded = false }: { initialId?: string; embedded?: boolean }) {
  const { data, error } = useCapabilities()
  const [selected, setSelected] = useState<string | null>(initialId ?? lastCapabilityLink()?.capabilityId ?? null), [tab, setTab] = useState('overview'), [query, setQuery] = useState(''), [filter, setFilter] = useState('all')
  const [editor, setEditor] = useState<{ id?: string } | null>(null), [role, setRole] = useState<string | null>(null), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { const open = (event: Event) => { const link = (event as CustomEvent<CapabilityLink>).detail; if (link.section === 'capability-center') setSelected(link.capabilityId ?? null) }; window.addEventListener('workbench-capability-link', open); return () => window.removeEventListener('workbench-capability-link', open) }, [])
  const run = async (fn: () => Promise<unknown>) => { setBusy(true); setMessage(''); try { await fn() } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } finally { setBusy(false) } }
  if (!data) return <div className={s.page}><p role={error ? 'alert' : 'status'}>{error || '正在读取能力数据…'}</p><button className={s.button} onClick={() => void capabilityClient.refresh()}>重新加载</button></div>
  const item = data.state.capabilities.find(c => c.id === selected)
  const linked = (id: string) => data.state.roles.filter(r => r.draft.capabilities.some(b => b.capabilityId === id) || latest(r.versions)?.capabilities.some(b => b.capabilityId === id))
  const visible = data.state.capabilities.filter(c => (filter !== 'pinned' || c.pinned) && (filter !== 'pending' || !c.enabled || !c.versions.length || data.health.state !== 'ready') && (filter !== 'unused' || !linked(c.id).length) && `${c.draft.name} ${c.draft.description}`.includes(query)).sort((a, b) => Number(b.pinned) - Number(a.pinned))
  return <section className={s.page} data-capability-center>
    {!embedded && <div className={s.heading}><div><h2>能力中心</h2><span className={s.muted}>编辑能力、组合组件，再装配到岗位助手。</span></div><button className={`${s.button} ${s.primary}`} onClick={() => setEditor({})}>＋ 创建能力</button></div>}
    {(error || message) && <p role="alert" className={s.error}>{message || error}</p>}
    {item ? <><button className={s.button} onClick={() => setSelected(null)}>← 全部能力</button><div className={s.heading} style={{ marginTop: 18 }}><div className={s.actions}><CapabilityGlyph/><div><h3>{item.draft.name}</h3><span className={s.muted}>{item.source === 'builtin' ? '内置能力' : '我的能力'} · {item.versions.length ? `v${latest(item.versions)!.version}` : '未发布草稿'}</span></div></div><div className={s.actions}><button className={s.button} onClick={() => setEditor({ id: item.id })}>编辑能力</button><button className={s.button} disabled={busy} onClick={() => void run(async () => { const id = await capabilityClient.command({ type: 'capability.copy', id: item.id }); setSelected(id); setEditor({ id }) })}>复制为我的能力</button></div></div><p>{item.draft.description}</p>
      <div className={s.tabs}>{[['overview', '概览与连接'], ['instructions', '使用说明'], ['defaults', '默认配置'], ['components', '关联组件'], ['roles', '使用岗位']].map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value!)}>{label}</button>)}</div>
      {tab === 'overview' && <><div className={s.row}><div><strong>{item.enabled ? data.health.message : '此能力已停用'}</strong><small>检测时间：{data.health.checkedAt ? new Date(data.health.checkedAt).toLocaleString() : '尚未检测'}</small></div><div className={s.actions}><button className={s.button} disabled={busy} onClick={() => void run(() => capabilityClient.check())}>检测连接</button><button className={s.button} disabled={busy} onClick={() => void run(() => capabilityClient.check(true))}>启动本地连接</button></div></div><label className={s.check}><input type="checkbox" checked={item.enabled} disabled={busy} onChange={e => void run(() => capabilityClient.command({ type: 'capability.toggle', id: item.id, enabled: e.target.checked }))}/>启用此能力</label><p className={s.muted}>影响范围：{linked(item.id).length} 个岗位、{data.tasks.filter(t => linked(item.id).some(r => r.id === t.roleId) && t.status !== 'stopped').length} 个活动会话。停用将立即阻止后续调用，并停止相关浏览器任务；保留配置与岗位引用。</p><div className={s.row}><span>{linked(item.id).length} 个岗位引用</span><button className={s.button} onClick={() => setTab('roles')}>查看岗位 →</button></div></>}
      {tab === 'instructions' && <><p style={{ whiteSpace: 'pre-wrap' }}>{item.draft.instructions || '尚未填写使用说明。'}</p><button className={s.button} onClick={() => setEditor({ id: item.id })}>编辑说明</button></>}
      {tab === 'defaults' && <><p>已发布动作：{actionsOf(latest(item.versions)).map(a => actionNames[a]).join('、') || '无'}</p><p className={s.notice}>岗位可覆盖为更少的动作。点击、填写、提交和站点白名单尚未开放。</p><button className={s.button} onClick={() => setEditor({ id: item.id })}>编辑组件与动作</button></>}
      {tab === 'components' && <ComponentRelations data={data} capabilityId={item.id}/>}
      {tab === 'roles' && <>{linked(item.id).map(r => <div className={s.row} key={r.id}><div><strong>{r.draft.name}</strong><small>{r.versions.length ? `已发布 v${latest(r.versions)!.version}` : '草稿'} · {r.enabled ? '启用' : '停用'}</small></div><button className={s.button} onClick={() => setRole(r.id)}>编辑岗位 →</button></div>)}{!linked(item.id).length && <p className={s.empty}>尚无岗位使用此能力。</p>}</>}
    </> : <><input className={s.search} aria-label="搜索能力" placeholder="搜索能力名称或用途" value={query} onChange={e => setQuery(e.target.value)}/><div className={s.tabs}>{[['all','全部'],['pinned','置顶'],['pending','待就绪'],['unused','未使用']].map(([value,label]) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value!)}>{label}</button>)}</div><div className={s.grid}>{visible.map(c => <article className={s.card} key={c.id}><div className={s.heading} style={{ marginBottom: 0 }}><CapabilityGlyph/><button className={s.button} aria-label={`置顶 ${c.draft.name}`} aria-pressed={c.pinned} onClick={() => void run(() => capabilityClient.command({ type: 'capability.pin', id: c.id, pinned: !c.pinned }))}>{c.pinned ? '★' : '☆'}</button></div><h3>{c.draft.name}</h3><p className={s.muted}>{c.draft.description}</p><span className={s.badge}>{!c.enabled ? '已停用' : !c.versions.length ? '草稿' : data.health.state === 'ready' ? '可使用' : '待连接'} · {linked(c.id).length} 个岗位</span><div className={s.actions}><button className={s.button} onClick={() => { setSelected(c.id); setTab('overview') }}>管理能力 →</button></div></article>)}</div>{!visible.length && <p className={s.empty}>没有符合条件的能力。</p>}<p className={s.muted}>当前真实适配：BrowserSkill。文档、表格、知识库等组件将在适配完成后加入。</p></>}
    {editor && <CapabilityEditor key={editor.id ?? 'new'} id={editor.id} data={data} onClose={() => setEditor(null)} onSaved={setSelected}/>}
    {role && <ManagedRoleEditor id={role} onClose={() => setRole(null)}/>}
  </section>
}
