import { RequirementsFileDrop } from './RequirementsFileDrop.tsx'
import React, { useEffect, useRef, useState } from 'react'
import { PillCheckbox } from '../../../../shared/client/PillCheckbox.tsx'
import { defaultRequirementSections, requirementSectionContent, type RequirementCommand, type RequirementSection, type RequirementTask } from '../../../dsh-capabilities/src/core/requirements-model.ts'
import { useCompositionSort } from './useCompositionSort.ts'
import s from './RequirementsAssistant.module.css'

type Props={task:RequirementTask|null;busy:boolean;mode:'quick'|'guided';view:'setup'|'result';onCommand:(c:RequirementCommand)=>Promise<RequirementTask|undefined>;onGuide:(instruction:string)=>void;onFiles?:(files:File[])=>Promise<void>}
export function RequirementsNotebook({task,busy,mode,view,onCommand,onGuide,onFiles}:Props){
  const [editing,setEditing]=useState(false),[rows,setRows]=useState<RequirementSection[]>([]),[projectPath,setProjectPath]=useState(''),[ledger,setLedger]=useState(true),[step,setStep]=useState(0),[projectOpen,setProjectOpen]=useState(false)
  const baseRevision=useRef<number|undefined>(undefined),dialog=useRef<HTMLElement>(null)
  useEffect(()=>{if(!editing)return;const previous=document.activeElement as HTMLElement|null;dialog.current?.querySelector<HTMLElement>('button')?.focus();return()=>previous?.focus()},[editing])
  const sections=task?.sections??defaultRequirementSections(),enabled=sections.filter(x=>x.enabled)
  useEffect(()=>{setProjectPath(task?.project?.path??'');setLedger(task?.project?.ledger??true)},[task?.project?.path,task?.project?.ledger])
  const change=(id:string,patch:Partial<RequirementSection>)=>setRows(current=>current.map(r=>r.id===id?{...r,...patch}:r))
  const sort=useCompositionSort((id,target)=>setRows(current=>{const result=[...current],a=result.findIndex(r=>r.id===id),b=result.findIndex(r=>r.id===target);const [row]=result.splice(a,1);result.splice(b,0,row);return result}),rows.map(x=>x.id))
  const edit=()=>{baseRevision.current=task?.dataRevision;setRows(structuredClone(sections).map(r=>({...r,content:task?requirementSectionContent(r,task):r.content})));setEditing(true)}
  const current=enabled[Math.min(step,Math.max(enabled.length-1,0))]
  return <section className={s.notebook}>
    {view==='setup'&&<>
      <div className={s.toolbar}><button onClick={()=>setProjectOpen(!projectOpen)}>{task?.project?'项目：'+task.project.path.split(/[\\/]/).pop():'关联本地项目（可选）'}</button><button onClick={edit}>整理内容 · 已选 {enabled.length} 项</button><span className={s.muted}>{task?.project?.ledger?'自动维护 '+task.project.ledgerName:'未关联项目也可直接分析'}</span></div>
      {projectOpen&&<div className={s.card}><h3>关联项目文件夹</h3><label className={s.field}><span>项目文件夹路径</span><input aria-label="项目文件夹路径" value={projectPath} placeholder="例如 C:\\项目\\语音助手" onChange={e=>setProjectPath(e.target.value)}/></label><label className={s.check}><PillCheckbox checked={ledger} onChange={e=>setLedger(e.target.checked)}/>在项目根目录自动维护 PERF_PLAN.md</label><p className={s.muted}>沿用已有同名台账；仅更新当前需求记录，保留其他内容。关联时读取根目录说明和已有台账；其余文件可自行选择加入资料。</p><div className={s.toolbar}><button disabled={busy||!projectPath.trim()} onClick={async()=>{if(await onCommand({type:'project.attach',path:projectPath.trim(),ledger}))setProjectOpen(false)}}>关联项目</button>{task?.project&&<button disabled={busy} onClick={()=>void onCommand({type:'project.detach'})}>解除关联</button>}<button onClick={()=>setProjectOpen(false)}>暂不关联</button></div></div>}
      {onFiles&&<RequirementsFileDrop busy={busy} onFiles={onFiles}/>}
      {!!task?.materials.some(m=>!m.removed)&&<ul className={s.fileTags} aria-label="已选参考资料">{task.materials.filter(m=>!m.removed).map(m=><li key={m.id} className={s.fileTag}><span title={m.name}>{m.name}</span><button type="button" disabled={busy} aria-label={'移除资料 '+m.name} title={'移除 '+m.name} onClick={()=>void onCommand({type:'material.remove',id:m.id,removed:true})}><svg viewBox="0 0 16 16" width="12" height="12" aria-hidden="true"><path d="m4 4 8 8M12 4l-8 8" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/></svg></button></li>)}</ul>}
      {mode==='guided'&&current&&<div className={s.guide}><div className={s.toolbar}>{enabled.map((r,i)=><button key={r.id} aria-pressed={i===step} onClick={()=>setStep(i)}>{i+1}. {r.title}</button>)}</div><h3>{current.title}</h3><p>{current.guidance}</p><div className={s.toolbar}><button disabled={busy} onClick={()=>onGuide('请围绕「'+current.title+'」逐步引导，先整理现有信息，再问必要的问题。')}>围绕此项继续</button><button onClick={edit}>编辑整理内容</button>{step<enabled.length-1&&<button onClick={()=>setStep(step+1)}>暂时跳过，下一项</button>}</div></div>}
    </>}
    {view==='result'&&<><div className={s.sectionHead}><div><h2>当前需求结果</h2><p>随讨论自动更新，可直接编辑和交付。</p></div><button disabled={busy} onClick={edit}>编辑内容与栏目</button></div>{enabled.map(r=><section className={s.card} key={r.id}><h3>{r.title}</h3><p>{task?requirementSectionContent(r,task)||'待补充':'待补充'}</p></section>)}</>}
    {task?.project?.error&&<div role="alert" className={s.error}>需求已保存，台账同步失败：{task.project.error}<button disabled={busy} onClick={()=>void onCommand({type:'project.refresh'})}>重试同步</button></div>}
    {editing&&<div className={s.overlay}><section ref={dialog} className={s.dialog} role="dialog" aria-modal="true" aria-label="整理内容配置" onKeyDown={e=>{if(e.key==='Escape'&&!sort.sorting)setEditing(false);if(e.key==='Tab'){const els=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,[tabindex="0"]')??[]),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header><h2>整理哪些内容</h2><button aria-label="关闭整理内容配置" onClick={()=>setEditing(false)}>×</button></header><div className={s.dialogBody}><p className={s.muted}>默认六项，可取消、增加和拖动整项排序。取消选中保留内容。</p><div ref={sort.root}>{rows.map((r,index)=><div key={r.id} data-composition-row={r.id} tabIndex={0} aria-label={'调整顺序：'+r.title} className={s.sectionRow} style={sort.style(r.id)} onPointerDown={e=>sort.start(r.id,e)} onClickCapture={sort.click} onKeyDown={e=>sort.key(r.id,e)} data-dragging={sort.sorting?.id===r.id} data-target={sort.sorting?.target===r.id}>
      <div className={s.toolbar}><span>{index+1}</span><PillCheckbox aria-label={'选择栏目 '+r.title} checked={r.enabled} onChange={e=>change(r.id,{enabled:e.target.checked})}/><input aria-label={'栏目名称 '+(index+1)} value={r.title} onChange={e=>change(r.id,{title:e.target.value})}/></div><input aria-label={'栏目说明 '+(index+1)} value={r.guidance} placeholder="希望整理什么（可选）" onChange={e=>change(r.id,{guidance:e.target.value})}/>{view==='result'&&<textarea aria-label={'编辑 '+r.title} value={r.content} rows={4} onChange={e=>change(r.id,{content:e.target.value})}/>}</div>)}</div>{sort.sorting&&!sort.sorting.keyboard&&<div className={s.sortPreview} style={{left:sort.sorting.x,top:sort.sorting.y}}>{rows.find(r=>r.id===sort.sorting?.id)?.title}</div>}{sort.sorting&&<p role="status">正在调整栏目顺序；空格放下，Esc 取消</p>}<button disabled={rows.length>=30} onClick={()=>setRows(current=>[...current,{id:crypto.randomUUID(),title:'自定义栏目',guidance:'',enabled:true,content:''}])}>＋ 新增栏目</button></div><footer><button onClick={()=>setEditing(false)}>取消</button><button className={s.primary} disabled={busy||rows.some(r=>!r.title.trim())} onClick={async()=>{if(await onCommand({type:'sections.save',sections:rows,baseDataRevision:baseRevision.current}))setEditing(false)}}>保存</button></footer></section></div>}
  </section>
}
