export const roleZh = {
  rolesTitle: '岗位助手', rolesDescription: '为每一类工作，准备一位熟悉职责的助手。',
  rolesPreview: '界面预览', rolesCreate: '创建岗位助手', rolesExample: '示例岗位',
  rolesAnalyst: '需求分析助手', rolesSummary: '梳理办公业务需求，厘清流程与功能，明确待确认事项。',
  rolesTagOne: '需求梳理', rolesTagTwo: '流程分析', rolesTagThree: '结构化输出',
  rolesMarketing: '市场部助手', rolesMarketingSummary: '整理市场与客户信息，策划推广内容，协助跟进商机。',
  rolesMarketingTagOne: '市场洞察', rolesMarketingTagTwo: '营销策划', rolesMarketingTagThree: '客户沟通',
  rolesMarketingDuties: '协助整理市场动态、客户需求与竞品信息，构思推广方案和宣传文案，梳理客户沟通要点与商机跟进事项。',
  rolesMarketingRequirements: '区分已知事实、分析判断与待核实信息，不编造市场数据或客户反馈。\n文案贴合目标客户与使用场景，对外承诺须由业务人员确认。',
  rolesMarketingFormat: '一、目标与受众\n二、市场与客户洞察\n三、推广建议与内容草案\n四、跟进事项',
  rolesManager: '项目经理助手', rolesManagerSummary: '拆解项目计划，跟踪里程碑与风险，让团队协作更清晰。',
  rolesManagerTagOne: '计划拆解', rolesManagerTagTwo: '进度跟踪', rolesManagerTagThree: '风险管理',
  rolesManagerDuties: '协助明确项目目标与交付范围，拆解任务、依赖和里程碑，整理进度周报、会议纪要及风险清单。',
  rolesManagerRequirements: '以已确认的范围、时间和资源为依据，不擅自承诺工期或分配责任人。\n明确任务依赖、阻塞事项和待决策问题，缺失信息标注待确认。',
  rolesManagerFormat: '一、项目目标与当前进展\n二、任务计划与里程碑\n三、风险及阻塞事项\n四、下一步行动与待确认事项',
  rolesDeveloper: '开发助手', rolesDeveloperSummary: '梳理技术实现，辅助代码分析与问题定位，完善测试思路。',
  rolesDeveloperTagOne: '技术设计', rolesDeveloperTagTwo: '代码分析', rolesDeveloperTagThree: '测试建议',
  rolesDeveloperDuties: '协助将明确需求转为技术方案，分析代码结构与问题原因，提供实现建议、代码示例和测试要点。',
  rolesDeveloperRequirements: '结合已提供的技术栈、接口和项目约束，不假设未确认的实现。\n区分建议、示例与实际执行结果；未经运行的代码和测试明确标注未验证。',
  rolesDeveloperFormat: '一、需求理解与技术方案\n二、实现步骤或代码示例\n三、测试要点\n四、风险与待确认事项',
  rolesConfigure: '查看配置', rolesExisting: 'Agent 预设',
  rolesExistingHint: '继续管理已有预设及其配置。',
  rolesNotice: '当前为界面预览，岗位配置暂不保存，也不会用于实际对话。',
  rolesChoose: '选择对话助手', rolesChooseHint: '根据本次工作，选择合适的助手。',
  rolesChatSummary: '日常问答、写作与灵感交流', rolesSelected: '已选择', rolesSelect: '预览此岗位',
  rolesSwitchHint: '开始对话后如需切换助手，请新建对话。', rolesBack: '返回助手列表',
  rolesClose: '关闭', rolesEdit: '岗位配置', rolesEditHint: '用清晰的职责、要求和输出格式，定义助手如何协助工作。',
  rolesName: '助手名称', rolesNamePlaceholder: '例如：需求分析助手',
  rolesColor: '卡片颜色', rolesCustomColor: '自定义颜色', rolesColorHint: '选择常用颜色，或打开调色盘；右侧即时预览。',
  rolesDuties: '岗位职责', rolesDutiesPlaceholder: '说明助手负责什么工作、服务哪些业务场景',
  rolesRequirements: '工作要求', rolesRequirementsPlaceholder: '说明必须遵守的规则，以及需要注意的边界',
  rolesFormat: '输出格式', rolesFormatPlaceholder: '说明回答应包含哪些内容，以及如何组织',
  rolesDutiesValue: '协助梳理核电企业办公业务的软件需求，理解业务目标、使用角色与操作流程，整理功能清单和待确认事项。',
  rolesRequirementsValue: '区分明确需求与待确认事项，不自行补充业务规则。\n信息不足时先提出澄清问题，使用业务人员易懂的语言。',
  rolesFormatValue: '一、业务目标\n二、操作步骤\n三、功能清单\n四、待确认事项',
  rolesLivePreview: '配置预览', rolesLiveHint: '填写内容会即时显示在这里',
  rolesUnnamed: '未命名岗位助手', rolesEmpty: '填写左侧内容后在这里预览',
  rolesCancel: '取消', rolesDone: '完成预览', rolesSave: '保存并启用',
  rolesSaveHint: '保存功能将在后续版本接入；关闭后不保留本次编辑。',
  rolesNewSessionHint: '配置修改将在新对话中使用。',
  rolesChatOnly: '当前仅预览岗位界面。切回普通聊天后即可发送消息。',
  rolesReturnChat: '切回普通聊天', rolesComposer: '输入工作需求（岗位对话尚未接通）',
}

export const roleEn: Record<keyof typeof roleZh, string> = {
  rolesTitle: 'Role assistants', rolesDescription: 'An assistant that understands each kind of work.',
  rolesPreview: 'UI preview', rolesCreate: 'Create role assistant', rolesExample: 'Example role',
  rolesAnalyst: 'Requirements analyst', rolesSummary: 'Clarify business needs, map workflows and list open questions.',
  rolesTagOne: 'Requirements', rolesTagTwo: 'Workflows', rolesTagThree: 'Structured output',
  rolesMarketing: 'Marketing assistant', rolesMarketingSummary: 'Organize market insights, plan campaigns and support customer outreach.',
  rolesMarketingTagOne: 'Market insights', rolesMarketingTagTwo: 'Campaign planning', rolesMarketingTagThree: 'Customer outreach',
  rolesMarketingDuties: 'Organize market trends, customer needs and competitor information. Draft campaign ideas, copy and follow-up actions.',
  rolesMarketingRequirements: 'Separate facts, interpretations and information to verify. Do not invent market data or customer feedback.\nAdapt copy to the audience and context. Business owners must confirm external commitments.',
  rolesMarketingFormat: '1. Goals and audience\n2. Market and customer insights\n3. Campaign suggestions and draft content\n4. Follow-up actions',
  rolesManager: 'Project manager assistant', rolesManagerSummary: 'Break down plans, track milestones and risks, and clarify team coordination.',
  rolesManagerTagOne: 'Project planning', rolesManagerTagTwo: 'Progress tracking', rolesManagerTagThree: 'Risk management',
  rolesManagerDuties: 'Clarify project goals and scope. Break down tasks, dependencies and milestones. Draft progress reports, meeting notes and risk lists.',
  rolesManagerRequirements: 'Use confirmed scope, schedules and resources. Do not invent deadlines or assign owners without confirmation.\nIdentify dependencies, blockers and decisions. Mark missing information as unconfirmed.',
  rolesManagerFormat: '1. Goals and progress\n2. Tasks and milestones\n3. Risks and blockers\n4. Next actions and open questions',
  rolesDeveloper: 'Development assistant', rolesDeveloperSummary: 'Explore implementation plans, analyze code and issues, and suggest tests.',
  rolesDeveloperTagOne: 'Technical design', rolesDeveloperTagTwo: 'Code analysis', rolesDeveloperTagThree: 'Test suggestions',
  rolesDeveloperDuties: 'Turn confirmed requirements into technical proposals. Analyze code and issues, suggest implementation steps, code examples and test cases.',
  rolesDeveloperRequirements: 'Use the supplied stack, interfaces and project constraints. Do not assume unconfirmed implementation details.\nDistinguish suggestions and examples from execution results. Clearly mark untested code and tests.',
  rolesDeveloperFormat: '1. Requirements and technical proposal\n2. Implementation steps or code examples\n3. Test considerations\n4. Risks and open questions',
  rolesConfigure: 'View configuration', rolesExisting: 'Agent presets', rolesExistingHint: 'Manage your existing presets and configurations.',
  rolesNotice: 'UI preview only. Role settings are not saved or used in conversations yet.',
  rolesChoose: 'Choose an assistant', rolesChooseHint: 'Choose an assistant for the work at hand.',
  rolesChatSummary: 'Everyday questions, writing and ideas', rolesSelected: 'Selected', rolesSelect: 'Preview this role',
  rolesSwitchHint: 'Start a new conversation to switch assistants after chatting begins.', rolesBack: 'Back to assistants',
  rolesClose: 'Close', rolesEdit: 'Role configuration', rolesEditHint: 'Define responsibilities, working rules and the expected output.',
  rolesName: 'Assistant name', rolesNamePlaceholder: 'e.g. Requirements analyst',
  rolesColor: 'Card color', rolesCustomColor: 'Custom color', rolesColorHint: 'Choose a swatch or open the color picker. Preview updates instantly.',
  rolesDuties: 'Responsibilities', rolesDutiesPlaceholder: 'Describe the work and business context',
  rolesRequirements: 'Working requirements', rolesRequirementsPlaceholder: 'Describe rules and boundaries',
  rolesFormat: 'Output format', rolesFormatPlaceholder: 'Describe the content and structure of responses',
  rolesDutiesValue: 'Help clarify software requirements for office workflows in a nuclear power enterprise. Identify business goals, user roles, workflows, features and open questions.',
  rolesRequirementsValue: 'Separate confirmed requirements from open questions. Do not invent business rules.\nAsk for clarification when information is missing. Use clear business language.',
  rolesFormatValue: '1. Business goals\n2. Workflow steps\n3. Feature list\n4. Open questions',
  rolesLivePreview: 'Configuration preview', rolesLiveHint: 'Updates as you type',
  rolesUnnamed: 'Untitled role assistant', rolesEmpty: 'Fill in the form to preview its content here',
  rolesCancel: 'Cancel', rolesDone: 'Finish preview', rolesSave: 'Save and enable',
  rolesSaveHint: 'Saving will be added later. Closing discards these edits.', rolesNewSessionHint: 'Configuration changes will apply to new conversations.',
  rolesChatOnly: 'This role is a UI preview. Switch back to Chat to send messages.',
  rolesReturnChat: 'Switch back to Chat', rolesComposer: 'Describe your task (role chat is not connected yet)',
}
