import { afterEach, describe, expect, it } from 'vitest'
import { mkdtemp, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { components, initialState, references } from '../src/core/model.ts'
import { relatedComponents, pluginReferences, componentPublishIssues, type ComponentActivity } from '../src/core/component-registry.ts'
import { ComponentRegistryStore } from '../src/host/component-registry.ts'
import { CapabilityStore } from '../src/host/store.ts'
import { allowedActions, wasRevoked } from '../src/core/policy.ts'

const stores: CapabilityStore[]=[]
function browserRole(state: ReturnType<typeof initialState>) { const value={ name:'浏览器岗位', color:'#4F73E8', duties:'', requirements:'', format:'', capabilities:[{capabilityId:'browser',version:1,enabled:true}] }; const role={id:'browser-role',enabled:true,draft:value,versions:[{...structuredClone(value),version:1,preset:'browser-role-v1',createdAt:new Date().toISOString()}]};state.roles.push(role);return role }
afterEach(async()=>{for(const store of stores.splice(0))await store.close()})
async function setup(){const directory=await mkdtemp(join(tmpdir(),'component-registry-')),store=new CapabilityStore(directory);await store.init();stores.push(store);let tasks:ComponentActivity[]=[];const registry=new ComponentRegistryStore(directory,()=>store.snapshot(),async()=>tasks);await registry.init();store.componentRestrictions=()=>registry.snapshot().metadata;store.publishIssues=ids=>componentPublishIssues(store.snapshot(),registry.snapshot(),ids);return {directory,store,registry,setTasks:(value:ComponentActivity[])=>{tasks=value}}}
const send=(r:ComponentRegistryStore,body:Record<string,unknown>)=>r.command({...body,operationId:randomUUID()})
async function lifecycle(r:ComponentRegistryStore,id:string,action:string){const preview=await r.preview(id,action);return send(r,{type:'component.'+action,id,token:preview.token,confirm:true})}
describe('exact component and plugin relationships',()=>{
 it('keeps parent package, browser export and similarly prefixed modules distinct',()=>{expect(relatedComponents('@linxin666/dsh-capabilities').map(c=>c.id)).toEqual(['developer-files','developer-checks','meeting-asr','requirements-service']);expect(relatedComponents('@linxin666/dsh-capabilities/browser').map(c=>c.id)).toEqual(['browserskill']);expect(relatedComponents('@linxin666/dsh-capabilities-unknown')).toEqual([])})
 it('unions every supplied component without duplicate capability counts',()=>{const result=pluginReferences(initialState(),'@linxin666/dsh-capabilities');expect(result.capabilities.map(c=>c.id)).toEqual(['developer-workspace','meeting-transcription','requirements-analysis']);expect(result.components).toHaveLength(4);expect(pluginReferences(initialState(),'@linxin666/dsh-capabilities/browser').capabilities.map(c=>c.id)).toEqual(['browser'])})
 it('retains historical role references and resolves the bound capability version',()=>{const state=initialState(),role=browserRole(state);role.draft.capabilities=[];role.versions.push({...structuredClone(role.versions[0]),version:2,capabilities:[]});expect(references(state,'browserskill').roles).toContainEqual(role)})
})
describe('component catalog writer and lifecycle',()=>{
 it('keeps metadata independent from capability state and reloads it',async()=>{const {registry,store,directory}=await setup(),before=await readFile(join(directory,'state.json'),'utf8');await send(registry,{type:'metadata.save',id:'developer-files',revision:0,base:{},patch:{name:'项目读写',category:'开发'}});expect(await readFile(join(directory,'state.json'),'utf8')).toBe(before);const reopened=new ComponentRegistryStore(directory,()=>store.snapshot(),async()=>[]);await reopened.init();expect(reopened.snapshot().metadata['developer-files'].name).toBe('项目读写')})
 it('merges independent fields and rejects conflicting fields without losing the first edit',async()=>{const {registry}=await setup();await send(registry,{type:'metadata.save',id:'developer-files',revision:0,base:{},patch:{name:'项目读写'}});await send(registry,{type:'metadata.save',id:'developer-files',revision:0,base:{},patch:{pinned:true}});await expect(send(registry,{type:'metadata.save',id:'developer-files',revision:0,base:{},patch:{name:'覆盖名称'}})).rejects.toMatchObject({status:409});expect(registry.snapshot().metadata['developer-files']).toMatchObject({name:'项目读写',pinned:true})})
 it('allows draft repair but blocks publication of retired components at the backend',async()=>{const {registry,store}=await setup(),browser=store.snapshot().capabilities.find(c=>c.id==='browser')!;await lifecycle(registry,'browserskill','retire');await store.command(store.snapshot().revision,{type:'capability.save',id:browser.id,definition:browser.draft,publish:false});await expect(store.command(store.snapshot().revision,{type:'capability.save',id:browser.id,definition:browser.draft,publish:true})).rejects.toThrow('回收站');expect(store.snapshot().capabilities.find(c=>c.id==='browser')!.versions).toHaveLength(1);await lifecycle(registry,'browserskill','restore');await store.command(store.snapshot().revision,{type:'capability.save',id:browser.id,definition:browser.draft,publish:true})})
 it('revokes old session permissions on global disable and never resurrects them after re-enable',async()=>{const {registry,store}=await setup(),state=store.snapshot(),role=browserRole(state);const version=role.versions[0];expect(allowedActions(state,role.id,version)).toContain('read');await lifecycle(registry,'browserskill','disable');state.componentRestrictions=registry.snapshot().metadata;expect(allowedActions(state,role.id,version)).not.toContain('read');await lifecycle(registry,'browserskill','enable');state.componentRestrictions=registry.snapshot().metadata;expect(wasRevoked(state,role.id,version,0)).toBe(true);expect(wasRevoked(state,role.id,version,Date.now()+1)).toBe(false)})
 it('invalidates an impact preview when a task appears or publication changes',async()=>{const {registry,store,setTasks}=await setup(),preview=await registry.preview('developer-files','disable');setTasks([{id:'task',name:'正在开发',kind:'developer',status:'running',componentIds:['developer-files']}]);await expect(send(registry,{type:'component.disable',id:'developer-files',token:preview.token,confirm:true})).rejects.toMatchObject({status:409});setTasks([]);await store.command(store.snapshot().revision,{type:'capability.pin',id:'browser',pinned:false});await expect(send(registry,{type:'component.disable',id:'developer-files',token:preview.token,confirm:true})).rejects.toMatchObject({status:409})})
 it('supports retry with the same operation ID, and only purges retired user candidates',async()=>{const {registry}=await setup(),command={type:'candidate.add',name:'搜索服务',provider:'@example/search',description:'',category:'检索',revision:0,operationId:randomUUID()};await registry.command(command);await registry.command(command);expect(registry.snapshot().candidates).toHaveLength(1);const id=registry.snapshot().candidates[0].id;await expect(lifecycle(registry,id,'purge')).rejects.toThrow('回收站');await lifecycle(registry,id,'retire');await lifecycle(registry,id,'purge');expect(registry.snapshot().candidates).toEqual([]);await expect(lifecycle(registry,components[0].id,'purge')).rejects.toThrow('内置组件')})
 it('rejects runtime identity edits and arbitrary lifecycle commands',async()=>{const {registry}=await setup();await expect(send(registry,{type:'metadata.save',id:'developer-files',revision:0,base:{},patch:{provider:'evil'}})).rejects.toThrow('运行标识');await expect(send(registry,{type:'component.execute',id:'developer-files'})).rejects.toThrow('无效')})
})
