import {afterEach,describe,it,expect} from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {ManagedSkills} from '../../dsh-skill-explorer/src/managed.ts'
import {RoleSkills} from '../src/host/role-skills.ts'
import {CapabilityStore} from '../src/host/store.ts'
import {allowedRoleSkills} from '../src/core/policy.ts'
import {emptyRole,roleHasUnpublishedChanges,type SkillBinding} from '../src/core/model.ts'
import {CapabilityRuntime} from '../src/host/runtime.ts'
const cleanups:(()=>Promise<void>)[]=[]
afterEach(async()=>{for(const close of cleanups.splice(0))await close()})
async function fixture(){const home=fs.mkdtempSync(path.join(os.tmpdir(),'role-skills-')),store=new CapabilityStore(path.join(home,'capabilities'));await store.init();cleanups.push(async()=>{await store.close();fs.rmSync(home,{recursive:true,force:true})});const managed=new ManagedSkills(home,()=>[home+'/project']),assets=new RoleSkills(home);return {home,store,managed,assets}}
function install(managed:ManagedSkills,body='first',scope='global'){const p=managed.inspect({scope,files:[{path:'review/SKILL.md',data:Buffer.from('---\nname: review\ndescription: Review requirements\n---\n'+body).toString('base64')},{path:'review/references/template.md',data:Buffer.from('Acceptance template').toString('base64')}]});managed.commit(p.id,[{key:p.candidates[0].key,mode:'update'}],true);const s=managed.read().skills.find(s=>s.scope===scope)!;return {id:s.id,name:s.name,hash:s.hash,enabled:true} satisfies SkillBinding}
async function publish(store:CapabilityStore,skills:SkillBinding[],id?:string){const r=await store.command(store.snapshot().revision,{type:'role.save',id,definition:{...emptyRole(),name:'Review role',skills},publish:true});return r.state.roles.find(s=>s.id===r.id)!}
describe('role skill binding and execution',()=>{
 it('persists bindings, preserves published execution while drafts change and restores after restart',async()=>{const {store,managed}=await fixture(),binding=install(managed),role=await publish(store,[binding]);await store.command(store.snapshot().revision,{type:'role.save',id:role.id,definition:{...role.draft,skills:[]},publish:false});const changed=store.snapshot().roles.find(r=>r.id===role.id)!;expect(roleHasUnpublishedChanges(changed)).toBe(true);expect(allowedRoleSkills(store.snapshot(),role.id,role.versions[0])).toEqual([binding]);await store.close();await store.init();expect(store.snapshot().roles.find(r=>r.id===role.id)!.draft.skills).toEqual([])})
 it('keeps the pinned version after multiple imports',async()=>{const {managed,assets}=await fixture(),binding=install(managed);install(managed,'second');install(managed,'third');expect(JSON.parse(assets.load(binding)).content).toContain('first');expect(assets.resource(binding,'references/template.md')).toBe('Acceptance template')})
 it('rejects resource traversal, missing files, outside projects and disabled skills only on use',async()=>{const {home,managed,assets}=await fixture(),binding=install(managed,'first',home+'/project');expect(()=>assets.load(binding,home+'/other')).toThrow('工作项目');expect(()=>assets.resource(binding,'../state.json',home+'/project')).toThrow('资源读取失败');expect(()=>assets.resource(binding,'missing.md',home+'/project')).toThrow('资源不存在');managed.change(binding.id,managed.read().revision,'enabled',false);expect(()=>assets.load(binding,home+'/project')).toThrow('技能已停用')})
 it('does not grant an unrecorded asset hash even if a file exists',async()=>{const {managed,assets}=await fixture(),binding=install(managed);expect(()=>assets.load({...binding,hash:'0'.repeat(64)})).toThrow('版本不存在')})
 it('prevents role removals followed by re-additions from reauthorizing old sessions',async()=>{const {store,managed}=await fixture(),binding=install(managed),role=await publish(store,[binding]);await publish(store,[],role.id);const newest=await publish(store,[binding],role.id);expect(allowedRoleSkills(store.snapshot(),role.id,role.versions[0])).toEqual([]);expect(allowedRoleSkills(store.snapshot(),role.id,newest.versions.at(-1)!)).toEqual([binding])})
 it('saves and publishes without probing skill files or connections',async()=>{const {store}=await fixture();const role=await publish(store,[{id:'11111111-1111-4111-8111-111111111111',name:'missing',hash:'a'.repeat(64),enabled:true}]);expect(role.versions).toHaveLength(1)})
 it('rejects duplicate bindings while keeping legacy roles unchanged',async()=>{const {store,managed}=await fixture(),binding=install(managed),before=store.snapshot();await expect(publish(store,[binding,binding])).rejects.toThrow('重复');expect(store.snapshot()).toEqual(before);expect(before.roles.every(r=>!Object.hasOwn(r.draft,'skills'))).toBe(true)})
 it('loads custom skills and resources without a BrowserSkill provider or unrelated tools',async()=>{const {store,managed,home}=await fixture(),binding=install(managed),role=await publish(store,[binding]),events=new Map(),definitions=new Map();const noop=()=>{};const ctx={tools:{guard:()=>noop},on:(name:string,fn:unknown)=>{events.set(name,fn);return noop},agents:{list:()=>[]}};const runtime=new CapabilityRuntime(ctx as never,store,{bskPath:'',bskHome:'',port:0});await runtime.init();const agent={id:'test',session:{header:{agentPreset:role.versions[0].preset,createdAt:Date.now()+1,cwd:home},snapshotEvents:()=>[]},ctx:{get:()=>undefined,tools:{guard:()=>noop,register:(d:any)=>{definitions.set(d.name,d);return noop}}}};events.get('agent/created')({agent});expect([...definitions.keys()]).toEqual(['skill','skill_resource']);const exec=(name:string,args:unknown)=>({agent,name,arguments:args,signal:new AbortController().signal,callId:'test'});expect(await definitions.get('skill').execute({name:'review'},exec('skill',{name:'review'}))).toContain('first');expect(await definitions.get('skill_resource').execute({name:'review',path:'references/template.md'},exec('skill_resource',{name:'review',path:'references/template.md'}))).toBe('Acceptance template');expect(runtime.authorize(exec('skill',{name:'foreign'}) as never)).toContain('未绑定')})
 it('supplies specialized workflows with the same versioned instructions and template',async()=>{const {store,managed,assets}=await fixture(),binding=install(managed),role=await publish(store,[binding]);expect(assets.guidance(store.snapshot(),role.id,role.versions[0])).toContain('Acceptance template');expect(assets.guidance(store.snapshot(),role.id,{...role.versions[0],skills:[]})).toBe('');managed.change(binding.id,managed.read().revision,'enabled',false);expect(()=>assets.guidance(store.snapshot(),role.id,role.versions[0])).toThrow('技能已停用')})
})

describe('skill usage settings',()=>{
 it('saves role selection atomically as drafts and leaves published skills intact',async()=>{const {store,managed}=await fixture(),b=install(managed),role=await publish(store,[]);await store.command(store.snapshot().revision,{type:'role.skills',skillId:b.id,roleIds:[role.id]});const r=store.snapshot().roles.find(r=>r.id===role.id)!;expect(r.draft.skills).toEqual([b]);expect(r.versions[0].skills).toEqual([]);const before=store.snapshot();await expect(store.command(before.revision,{type:'role.skills',skillId:b.id,roleIds:['missing']})).rejects.toThrow();expect(store.snapshot()).toEqual(before)})
 it('inherits all-dialogue skills only after selection and pins versions by task creation',async()=>{const {store,managed,assets}=await fixture(),b=install(managed),role=await publish(store,[]),before=Date.now()-1;expect(assets.bindings(store.snapshot(),role.id,role.versions[0],Date.now())).toEqual([]);managed.change(b.id,managed.read().revision,'usage','all');const at=Date.now();expect(assets.bindings(store.snapshot(),role.id,role.versions[0],before)).toEqual([]);expect(assets.bindings(store.snapshot(),role.id,role.versions[0],at)).toEqual([b]);await new Promise(r=>setTimeout(r,5));install(managed,'second');expect(assets.bindings(store.snapshot(),role.id,role.versions[0],at)[0].hash).toBe(b.hash);expect(assets.bindings(store.snapshot(),role.id,{...role.versions[0],skills:[{...b,enabled:false}]},Date.now())).toEqual([])})
})

it('does not expand existing ordinary dialogue scope after enabling all-dialogue usage',async()=>{const {managed,assets}=await fixture(),binding=install(managed),before=Date.now()-1;managed.change(binding.id,managed.read().revision,'usage','all');expect(assets.ordinaryViolation(binding.name,before)).toContain('使用范围');expect(assets.ordinaryViolation(binding.name,Date.now()+1)).toBeUndefined();managed.change(binding.id,managed.read().revision,'usage','roles');expect(assets.ordinaryViolation(binding.name,Date.now()+1)).toContain('使用范围')})
